### PR TITLE
Update README with wiring information and fix markdown

### PR DESCRIPTION
**Pull request by karniv00l**
## Proposed changes:

- added information about pins outputs 
- added visual wiring example for v0.4 board with Arduino Mega (https://github.com/karniv00l/Ardu-Stim/blob/788f51264b1a95995ad1c5bced94491b99577ecb/docs/v04-wiring.png)
- MD style fixed according to linter (https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)

### CODE REVIEW

**Comment by karniv00l** [comment]
on second thought, this png might be an overkill 🤔

**Comment by noisymime** [comment]
Looks good to me and the image is fine (Though probably needs to be a little smaller). The only addition I'd add is that if you're using a Mega as the stim card, then the output pins will be different (52 an 53) rather than the ones mentioned.

**Comment by karniv00l** [comment]
I've added pins for mega and resized image to match githubs preview (with some padding)

**Comment by karniv00l** [comment]
And sorry, I wasn't aware that it supports Mega also

**Pull request merged**
